# Example configuration for the webserver
# at https://github.com/monopole/hello
commonLabels:
  app: hello
namespace: example-dev
resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- namespace.yaml