on:
  push:
    branches:
    - master
    # TODO: remove
    - re-write
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm install
    - run: npm run all
      env:
        KUSTOMIZE_PLUGIN_HOME: /tmp/kustomize
    - run: npm run package
    - name: Commit dist
      run: |
        set -x
        msg="Commiting dist"
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email action@github.com
        git add ./dist -f
        if [[ -z $(git status --porcelain) ]]; then
          echo "No changes."
          exit 0
        fi
        git fetch --unshallow
        if [[ "$(git log -n 1 | tail -n 1)" =~ "$msg" ]]; then
          exit 0 # this shouldn't happen - but prevent it recursively commiting forever
        fi
        git commit -m "$msg"
        git push origin HEAD:$GITHUB_REF
